### ISSUE TITLE
Provide AppImage for Linux

### ISSUE THREAD

**Issue by probonopd** [mmorainville/netsix#1]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Works for most Linux distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Just one format for all major distributions
- Works out of the box, no installation of runtimes needed (unlike Snap and Flatpak)
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)
- Works on Live ISOs (unlike Flatpak)
- Can use the same AppImages when dual-booting multiple distributions

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages. Many of them are using __electron-builder__, as is this project.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.

**Comment by mmorainville** [comment]
Hi @probonopd,

Thanks for your proposition. AppImage seems indeed interesting, but for now this projects, though it's using Electron, only works on Windows as it includes ffmpeg and other softwares binaries and that for now those binaries are only for Windows.

It is planned to make the app cross-platform in the near future, and it shouldn't be that hard, but for now we are more focusing on improving and stabilizing the existing functionalities.
So I'm rejecting you proposal for the moment, but will take a look at it again when we'll be ready to deploy on Linux.

Regards,
M.

**Comment by probonopd** [comment]
ffmpeg is also available for Linux ;-)

**Comment by mmorainville** [comment]
Yes of course. I just meant that we are only including the Windows binaries in the app for the moment. There is already nearly 30 MB of external softwares so adding binaries for Mac and Linux would even more increase the size of the app.

I was wondering if there was somehow a way of either building the binaries from the source when packaging the app with electron-builder or installing ffmpeg directly using the Squirrel installer. But it's a bit out of my comfort zone and I'll have to do some research to do that well. That's why we postponed it for now. :-)
